.gitignore
Makefile
README.md
examples/helloworld-cnab/bundle.json

- Ignore everything in `bin/` directory.
- Don't call `make` from inside `Makefile`.
- Update README with example based off hello world example from [duffle](https://github.com/deislabs/duffle).

Improve readme

---

cmd/cnab-to-oci/pull.go

Allows one to do:
```console
$ bin/cnab-to-oci pull ccrone/cnab@sha256:6cabd752cb01d2efb9485225baf7fc26f4322c1f45f537f76c5eeb67ba8d83e0 -o -
{
"name": "helloworld",
"version": "0.1.1",
"description": "A short description of your bundle",
"keywords": [
"helloworld",
"cnab",
"tutorial"
],
"maintainers": [
{
"name": "Jane Doe",
"email": "jane.doe@example.com",
"url": "https://example.com"
}
],
"invocationImages": [
{
"imageType": "docker",
"image": "ccrone/cnab@sha256:a59a4e74d9cc89e4e75dfb2cc7ea5c108e4236ba6231b53081a9e2506d1197b6",
"size": 942,
"mediaType": "application/vnd.docker.distribution.manifest.v2+json"
}
],
"images": null,
"parameters": null,
"credentials": null
}
```

Add option to output pull to stdout

---

cmd/cnab-to-oci/fixup.go
cmd/cnab-to-oci/pull.go
cmd/cnab-to-oci/push.go
e2e/e2e_test.go
remotes/resolver.go

When doing Fixups, we can have situations where only 1 of the source and target registries are insecure.
This brings the possibility to set the plainHTTP setting per-registry instead of globally.

Per-registry PlainHTTP setting support instead of global

---

Gopkg.lock
Gopkg.toml
Makefile
cmd/cnab-to-oci/fixup.go
cmd/cnab-to-oci/pull.go
cmd/cnab-to-oci/push.go
e2e/e2e_test.go
remotes/fixup.go
remotes/mount.go
remotes/promises.go
remotes/promises_test.go
remotes/resolver.go
vendor/github.com/containerd/containerd/images/handlers.go
vendor/github.com/containerd/containerd/remotes/docker/auth.go
vendor/github.com/containerd/containerd/remotes/docker/authorizer.go
vendor/github.com/containerd/containerd/remotes/docker/converter.go
vendor/github.com/containerd/containerd/remotes/docker/fetcher.go
vendor/github.com/containerd/containerd/remotes/docker/pusher.go
vendor/github.com/containerd/containerd/remotes/docker/resolver.go
vendor/github.com/containerd/containerd/remotes/docker/scope.go
vendor/github.com/containerd/containerd/remotes/handlers.go
vendor/golang.org/x/sync/semaphore/semaphore.go

This introduce an event sink instead of logging everything to os.Stderr.
The goal is for client code to control the rendering of events in a meaningfull way.
3 events are exposed:
- `CopyImageStart`: happens when the fixup logic starts working on an image
- `CopyImageEnd`: happens when the fixup logic ends working on an image (Error field is populated on error)
- `Progress`: a new progress snapshot has been recorded
The Client Code can choose the granularity of its display. The Progress snapshot exposes the whole graph of descriptor currently processed by the fixup logic.
Example of rich output that can be done:

Introduce an event sink and improve fixup

---

remotes/fixup.go
remotes/promises.go

In case of an error occuring in Fixup, there is a race condition where
we send an event after closing the event channel.
This is because the main task can complete (with an error) earlier than
other concurrent scheduled tasks running in the errgroup.
This adds a drain function to the errgroupScheduler to wait for all
goroutines to complete.

Fix write on closed channel error

---

Makefile

The  2 > nul hack on Windows is only there for using within a cmd.exe
console. Current Makefile does only work within git bash (or wsl) on
Windows, and they make a "nul" file appear as bash does not handle this
redirection with anything special.
Worse, `nul` is actually a reserved name on Windows, and most APIs can't
manipulate a file named `nul` (and thus to remove it, you must either
run git bash or wsl).
As both WSL and git bash allow to redirect to /dev/null, this PR treats
Windows in the same way as Unix.
Signed-off-by: Simon Ferquel <simon.ferquel@docker.com>

Don't write a `nul` file on Windows

---

Gopkg.lock
cmd/cnab-to-oci/push.go
remotes/fixup.go
remotes/fixup_test.go
remotes/typeless.go
vendor/github.com/docker/distribution/manifest/manifestlist/manifestlist.go

When we want to push every image (inovcation-image + component images) with a single platform support, this collapse multi-arch image references into platform-specific image manifests.
This makes pushing the bundle much lighter when referencing official images supporting many flavor of os/arch combinations.

Support single platform filter

---

remotes/pull.go

OCI manifests don't contain a mediaType field, and thus, when parsing it as as a docker image manifest, it failed.
The other conversion works, because, except for mediaType, a docker image manifest is a subset of an OCI manifest.

fix pull error when config is wrapped in an oci-manifest

---

cmd/cnab-to-oci/push.go

When pushing onto a registry accepting config media type
application/vnd.cnab.config.v1+json, containerd client lib emits a
warning: WARN[0015] reference for unknown type:
application/vnd.cnab.config.v1+json on stderr.
To avoid this, this PR set a muted logger to the push context

Mute containerd warnings on push

---

converter/convert.go
remotes/push_test.go
tests/helpers.go

range over a map starts from a random index, making the final order of
images random, this will in turn generate different digests when pushing
the index. With this change the list of images will have a stable order,
resulting in a same digest for multiple pushes.

Fix image ordering

---

converter/types.go
converter/types_test.go

While pushing the bundle configuration to a registry, we try first to use the OCI format with specific media type.
If it fails we try again with a more common media type, and if it fails we try a last time with Docker format.
All these fallbacks tries to reach maximum compatibility with all the deployed image registries.
But the fallback were not well configured, and the first one was missing. This is fixed now.

Fix bad manifest fallback configuration

---

Gopkg.lock
Gopkg.toml
vendor/github.com/deislabs/cnab-go/bundle/bundle.go
vendor/github.com/deislabs/cnab-go/bundle/parameters.go

We just cut a release of cnab-go to v0.2.0-beta1 so I thought I'd send a PR to bump cnab-to-oci as well.

Bumped cnab-go dep

---

converter/convert.go
converter/types.go
remotes/push_test.go
tests/helpers.go

This adds support for the bundle outputs field so that it's round tripped when a bundle with outputs defined is pushed/pulled to a registry.

Support bundle outputs

---

.circleci/config.yml
Dockerfile

* golang 1.12.9
* Alpine 3.10
* Docker CLI 19.03.1
Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>

Bumping CI dependencies

---

remotes/fixup_test.go
remotes/promises.go

- remove unused struct
- simplify `then` handler, there is no need for a select

Simple code cleanup

---

Gopkg.lock
Gopkg.toml
remotes/push.go
vendor/github.com/docker/cli/cli/config/config.go
vendor/github.com/docker/cli/cli/config/configfile/file.go
vendor/github.com/docker/cli/cli/config/credentials/credentials.go
vendor/github.com/docker/cli/cli/config/credentials/file_store.go
vendor/github.com/docker/cli/cli/config/credentials/native_store.go
vendor/github.com/docker/cli/cli/config/types/authconfig.go

Override `docker/cli` dependency to docker/cli@23446275646041f9b598d64c51be24d5d0e49376
This commit is a little more recent than the one provided by `deislabs/cnab-go` that is docker/cli@f95ca8e1ba6c22c9abcdbf65e8dcc39c53958bba
This target commit is the one that copies `types.AuthConfig` from docker api to docker cli.
By itself it's not an issue but it can be if `cnab-to-oci` is integrated in a context where a newer version of `docker/cli` is required.
See https://github.com/docker/cnab-to-oci/pull/76#discussion_r335174252 for example, and the same kind of issue exists in `docker/app` where both `cnab-to-oci` and a more recent `docker/cli` are used.

Update docker/cli to handle `types.AuthConfig`

---

internal/image_client.go
remotes/fixup.go
remotes/fixup_test.go
remotes/fixupoptions.go
remotes/mocks_test.go
remotes/push.go

In the case `contentDigest` is defined (for example after a build
by docker app) try to push local docker image from the digest.
In that case, the `image` of the service is not defined in the
bundle.json.
If `contentDigest` is empty, do the same thing as before, so try to resolve
and if it's not resolvable try to push.
The service name is now displayed in error messages to better understand
what's going on on failures.
Signed-off-by: Yves Brissaud <yves.brissaud@docker.com>

allow to push local docker images by digest

---

README.md

With 4f3cb87 (#76) and 5a97c84 (#78) `cnab-to-oci` is now able
to push images from local docker daemon image store.
Signed-off-by: Yves Brissaud <yves.brissaud@docker.com>

update README about new push behavior

---

remotes/pull.go

Simplify the error message returned when attempting to pull a CNAB that is not found reducing the current error message:
```
<image>: failed to resolve bundle manifest "docker.io/<image>:latest": docker.io/<image>:latest not found
```
To:
```
<image>: docker.io/<image>:latest: not found
```

Simplify the pull error returned on not found

---

remotes/fixup.go
remotes/fixup_test.go
remotes/fixupoptions.go
remotes/mocks_test.go

When we are doing the `fixup` of a bundle, apply relocation map when necessary.
Previous behaviour:
- resolve image
- if found, copy or mount
- if not found
- if image present in local docker image store
- push
The goal of this commit is to add one more condition, to copy/mount images that has been previously pushed from the local docker image store and so that can be resolved using the relocation map.
So the behaviour looks like:
- look at relocation map for entry corresponding to the image
- if found
- if resolved, copy and return from here
- if not found from relocation map or not resolvable
- resolve image from bundle definition
- if resolved, copy and return from here
- if not resolved but present in the local docker image store
- push
The affected workflow is the following:
1. …

fallback to relocation map when image is not found

---

Gopkg.lock
remotes/push.go

Used for the push using Docker's cli.
See https://github.com/docker/cli/blob/23446275646041f9b598d64c51be24d5d0e49376/cli/config/credentials/file_store.go#L32-L47 (current used revision) to have more information about this fix.
By example if you are logged on multiple registries, you can have something like that in your `config.json`.
```json
{
"auths": {
"https://index.docker.io/v1/": {},
"quay.io": {},
}
}
```
This fix allows to handle auth configurations with and without `http[s]://` prefix.

convert to hostname if needed when trying to authenticate

---

Gopkg.lock
Gopkg.toml

Signed-off-by: Silvin Lubecki <silvin.lubecki@docker.com>

Bump cnabio/cnab-go from v0.8.0-beta1 to v0.8.2-beta1

---

.circleci/config.yml

* adds a release job to the current circleci config
Adding in Draft as I'm a circleci newbie!  Cobbled together after quick looks at docs/examples... Perhaps @silvin-lubecki can lend a hand in review/testing/etc. ?
TODO: 
Contributes towards https://github.com/cnabio/cnab-to-oci/issues/90

feat(ci): add release job

---

converter/convert.go
go.mod
go.sum

Bundle.SchemaVersion was changed to a custom type, based on a string.

Bump cnab-go to v0.10.0-beta1

---

go.mod
remotes/mount.go
remotes/pull.go
remotes/push.go

when containderd is upgraded, tests started to break due to the changes in containerd's error handling. 
This PR switches error handling from "github.com/pkg/errors" to go native "errors" package

remotes: remove reference to pkg/errors

---

go.mod
remotes/fixup.go
remotes/resolver.go

This tweaks how we create a resolver so that we handle plain http connections, and TLS validation the same way as Docker.
* When a loopback address is specified as insecure, that should take precedence over it being plain http. So if I'm running a local registry with self-signed certificates, it should use the skipTLS http client, and not attempt to use plain http.
* All loopback addresses, not just localhost and 127.0.0.1, should default to plain http unless specified as insecure.
The impact is that you only need to specify that a registry is insecure when:
* You used self-signed certificates
* It uses plain http on a non-loopback address
When I was looking at the docker library we are using to create a resolver, I saw that we were using deprecated functionality. By using the Hosts …

Match insecure registry behavior from Docker
